//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiveFive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiveFive.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for instructions on how to reset your password..
        /// </summary>
        public static string ForgotPasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPasswordConfirmPageTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPasswordPageTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reset Email.
        /// </summary>
        public static string ForgotPasswordSubmitButton {
            get {
                return ResourceManager.GetString("ForgotPasswordSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email below..
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked, Lock expires: {0}.
        /// </summary>
        public static string LoginErrorMessageAccountLocked {
            get {
                return ResourceManager.GetString("LoginErrorMessageAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked for {0} hours due to {1} invalid logon attempts..
        /// </summary>
        public static string LoginErrorMessageAccountLockout {
            get {
                return ResourceManager.GetString("LoginErrorMessageAccountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification email has been sent to your registered email address..
        /// </summary>
        public static string LoginErrorMessageEmailNotVerified {
            get {
                return ResourceManager.GetString("LoginErrorMessageEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reCaptcha.
        /// </summary>
        public static string LoginErrorMessageInvalidCaptcha {
            get {
                return ResourceManager.GetString("LoginErrorMessageInvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password was invalid..
        /// </summary>
        public static string LoginErrorMessageInvalidEmailPassword {
            get {
                return ResourceManager.GetString("LoginErrorMessageInvalidEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string LoginErrorMessageInvalidTwoFactor {
            get {
                return ResourceManager.GetString("LoginErrorMessageInvalidTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string LoginForgotPasswordLink {
            get {
                return ResourceManager.GetString("LoginForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string LoginRegisterLink {
            get {
                return ResourceManager.GetString("LoginRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginSubmitButton {
            get {
                return ResourceManager.GetString("LoginSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your HiveFive account..
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please &lt;a href=&quot;/Account/Login&quot;&gt;click here to Log in&lt;/a&gt;.
        /// </summary>
        public static string RegisterConfirmMessage {
            get {
                return ResourceManager.GetString("RegisterConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string RegisterConfirmPageTitle {
            get {
                return ResourceManager.GetString("RegisterConfirmPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send registration confirmation email, if problem persists please contact &lt;a class=&quot;support-link&quot; href=&quot;/Support&quot;&gt;Support&lt;/a&gt;.
        /// </summary>
        public static string RegisterErrorMessageConfirmEmailSendFail {
            get {
                return ResourceManager.GetString("RegisterErrorMessageConfirmEmailSendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; already in use, please try a new Email..
        /// </summary>
        public static string RegisterErrorMessageEmailExists {
            get {
                return ResourceManager.GetString("RegisterErrorMessageEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName &apos;{0}&apos; already exists, please try a new Username..
        /// </summary>
        public static string RegisterErrorMessageUserNameExists {
            get {
                return ResourceManager.GetString("RegisterErrorMessageUserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        public static string RegisterSubmitButton {
            get {
                return ResourceManager.GetString("RegisterSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An activation email has been sent to your registered email address, please click the link to activate your HiveFive account..
        /// </summary>
        public static string RegisterSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Email.
        /// </summary>
        public static string RegisterSuccessPageTitle {
            get {
                return ResourceManager.GetString("RegisterSuccessPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new HiveFive account..
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please &lt;a href=&quot;/Account/Login&quot;&gt;click here to log in&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string ResetPasswordConfirmPageTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordPageTitle {
            get {
                return ResourceManager.GetString("ResetPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordSubmitButton {
            get {
                return ResourceManager.GetString("ResetPasswordSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXX-XXX-XXX.
        /// </summary>
        public static string ResetTwoFactorCodePlaceholder {
            get {
                return ResourceManager.GetString("ResetTwoFactorCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Recovery Code.
        /// </summary>
        public static string ResetTwoFactorErrorMessageInvalidCode {
            get {
                return ResourceManager.GetString("ResetTwoFactorErrorMessageInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset TwoFactor.
        /// </summary>
        public static string ResetTwoFactorPageTitle {
            get {
                return ResourceManager.GetString("ResetTwoFactorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset TwoFactor.
        /// </summary>
        public static string ResetTwoFactorSubmitButton {
            get {
                return ResourceManager.GetString("ResetTwoFactorSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your TwoFactor..
        /// </summary>
        public static string ResetTwoFactorTitle {
            get {
                return ResourceManager.GetString("ResetTwoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string ValidationErrorMessageInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationErrorMessageInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ValidationErrorMessageInvalidPasswordCompare {
            get {
                return ResourceManager.GetString("ValidationErrorMessageInvalidPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValidationErrorMessageInvalidPasswordLength {
            get {
                return ResourceManager.GetString("ValidationErrorMessageInvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Recovery Code.
        /// </summary>
        public static string ValidationErrorMessageInvalidRecoveryCode {
            get {
                return ResourceManager.GetString("ValidationErrorMessageInvalidRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName can only contain letters, digits and underscore.
        /// </summary>
        public static string ValidationErrorMessageInvalidUserName {
            get {
                return ResourceManager.GetString("ValidationErrorMessageInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required.
        /// </summary>
        public static string ValidationErrorMessageRequiredEmail {
            get {
                return ResourceManager.GetString("ValidationErrorMessageRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required.
        /// </summary>
        public static string ValidationErrorMessageRequiredOldPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMessageRequiredOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ValidationErrorMessageRequiredPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMessageRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Code is Required.
        /// </summary>
        public static string ValidationErrorMessageRequiredRecoveryCode {
            get {
                return ResourceManager.GetString("ValidationErrorMessageRequiredRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code is required.
        /// </summary>
        public static string ValidationErrorMessageRequiredSecurityCode {
            get {
                return ResourceManager.GetString("ValidationErrorMessageRequiredSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is required.
        /// </summary>
        public static string ValidationErrorMessageRequiredUserName {
            get {
                return ResourceManager.GetString("ValidationErrorMessageRequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code invalid or has expired.
        /// </summary>
        public static string ValidationErrorMessageSecurityCodeExpired {
            get {
                return ResourceManager.GetString("ValidationErrorMessageSecurityCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code must be between 4 and 8 digits.
        /// </summary>
        public static string ValidationErrorMessageSecurityCodeNumOnly {
            get {
                return ResourceManager.GetString("ValidationErrorMessageSecurityCodeNumOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Code.
        /// </summary>
        public static string VerifyTwoFactorEmailPlaceholder {
            get {
                return ResourceManager.GetString("VerifyTwoFactorEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator Code.
        /// </summary>
        public static string VerifyTwoFactorOtpPlaceholder {
            get {
                return ResourceManager.GetString("VerifyTwoFactorOtpPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify TwoFactor.
        /// </summary>
        public static string VerifyTwoFactorPageTitle {
            get {
                return ResourceManager.GetString("VerifyTwoFactorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string VerifyTwoFactorPinPlaceholder {
            get {
                return ResourceManager.GetString("VerifyTwoFactorPinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Code.
        /// </summary>
        public static string VerifyTwoFactorSubmitButton {
            get {
                return ResourceManager.GetString("VerifyTwoFactorSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your TwoFactor details below..
        /// </summary>
        public static string VerifyTwoFactorTitle {
            get {
                return ResourceManager.GetString("VerifyTwoFactorTitle", resourceCulture);
            }
        }
    }
}
