//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiveFive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TwoFactor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwoFactor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiveFive.Resources.TwoFactor", typeof(TwoFactor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateButtonCancel {
            get {
                return ResourceManager.GetString("CreateButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        public static string CreateButtonSendCode {
            get {
                return ResourceManager.GetString("CreateButtonSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string CreateButtonSubmit {
            get {
                return ResourceManager.GetString("CreateButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Code.
        /// </summary>
        public static string CreateButtonVerifyCode {
            get {
                return ResourceManager.GetString("CreateButtonVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address to use then click &apos;Send Code&apos;.
        ///_x0009__x0009__x0009__x0009__x0009__x0009__x0009__x0009_This email address must be different from your registered email address..
        /// </summary>
        public static string CreateFieldLabelEmail {
            get {
                return ResourceManager.GetString("CreateFieldLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code found on your device below to verify..
        /// </summary>
        public static string CreateFieldLabelOtp {
            get {
                return ResourceManager.GetString("CreateFieldLabelOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a 4 to 8 digit pin number..
        /// </summary>
        public static string CreateFieldLabelPin {
            get {
                return ResourceManager.GetString("CreateFieldLabelPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Type.
        /// </summary>
        public static string CreateFieldLabelType {
            get {
                return ResourceManager.GetString("CreateFieldLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code found in the sent email below to verify.
        ///Once verified you can continue to save your two factor security settings..
        /// </summary>
        public static string CreateFieldLabelVerifyEmail {
            get {
                return ResourceManager.GetString("CreateFieldLabelVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email two factor uses a second email address for security, when a two factor action is required a unique code is sent to this email address..
        /// </summary>
        public static string CreateLabelDescriptionEmail {
            get {
                return ResourceManager.GetString("CreateLabelDescriptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator two factor uses ther OTP protocol to create one-time use unique codes.
        ///There are many popular App solutions for OTP including Google Authenticator &amp; Authy..
        /// </summary>
        public static string CreateLabelDescriptionOtp {
            get {
                return ResourceManager.GetString("CreateLabelDescriptionOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin two factor uses a fixed 4-8 digit code for security, when a two factor action is required you will need to enter this code..
        /// </summary>
        public static string CreateLabelDescriptionPin {
            get {
                return ResourceManager.GetString("CreateLabelDescriptionPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan or enter your Authentication code below..
        /// </summary>
        public static string CreateLabelOtpQrcode {
            get {
                return ResourceManager.GetString("CreateLabelOtpQrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Security.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup two Factor.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be your registered email address..
        /// </summary>
        public static string ErrorMessageEmailNotAllowed {
            get {
                return ResourceManager.GetString("ErrorMessageEmailNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string ErrorMessageEmailRequired {
            get {
                return ResourceManager.GetString("ErrorMessageEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid email address..
        /// </summary>
        public static string ErrorMessageInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator code is required.
        /// </summary>
        public static string ErrorMessageOtpRequired {
            get {
                return ResourceManager.GetString("ErrorMessageOtpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured in OTP validation.
        /// </summary>
        public static string ErrorMessageOtpUnknown {
            get {
                return ResourceManager.GetString("ErrorMessageOtpUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code is required.
        /// </summary>
        public static string ErrorMessagePinRequired {
            get {
                return ResourceManager.GetString("ErrorMessagePinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinCode must be between 4 and 8 digits.
        /// </summary>
        public static string ErrorMessagePinValidation {
            get {
                return ResourceManager.GetString("ErrorMessagePinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send two factor email code to the email address provided..
        /// </summary>
        public static string ErrorMessageSendEmailCode {
            get {
                return ResourceManager.GetString("ErrorMessageSendEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is highly reccommended that you use two factor authentication..
        /// </summary>
        public static string ErrorMessageTextNoTwoFactor {
            get {
                return ResourceManager.GetString("ErrorMessageTextNoTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured sending twofactor code email, If problems persists please contact &lt;a href=&apos;/Support&apos;&gt;Support&lt;/a&gt;.
        /// </summary>
        public static string ErrorMessageTextSendEmail {
            get {
                return ResourceManager.GetString("ErrorMessageTextSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no two factor setup.
        /// </summary>
        public static string ErrorMessageTitleNoTwoFactor {
            get {
                return ResourceManager.GetString("ErrorMessageTitleNoTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Send Failed.
        /// </summary>
        public static string ErrorMessageTitleSendEmail {
            get {
                return ResourceManager.GetString("ErrorMessageTitleSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate your email two factor code..
        /// </summary>
        public static string ErrorMessageVerifyEmailCode {
            get {
                return ResourceManager.GetString("ErrorMessageVerifyEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verifiy your Authenticator code..
        /// </summary>
        public static string ErrorMessageVerifyOtpCode {
            get {
                return ResourceManager.GetString("ErrorMessageVerifyOtpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is required.
        /// </summary>
        public static string ErrorMessageVerifyRequired {
            get {
                return ResourceManager.GetString("ErrorMessageVerifyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor code entered is incorrecct or has expired, please try again..
        /// </summary>
        public static string InvalidTwoFactorText {
            get {
                return ResourceManager.GetString("InvalidTwoFactorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string RemoveButtonSubmit {
            get {
                return ResourceManager.GetString("RemoveButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To setup a new two factor method you must first remove the existing {0} two factor.
        ///If you have lost or can no longer access your current {0} please contact &lt;a href=&apos;/Support&apos;&gt;Support&lt;/a&gt; for assistance..
        /// </summary>
        public static string RemoveDescription {
            get {
                return ResourceManager.GetString("RemoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Code.
        /// </summary>
        public static string RemoveFieldEmailCode {
            get {
                return ResourceManager.GetString("RemoveFieldEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator Code.
        /// </summary>
        public static string RemoveFieldOtpCode {
            get {
                return ResourceManager.GetString("RemoveFieldOtpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string RemoveFieldPinCode {
            get {
                return ResourceManager.GetString("RemoveFieldPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your unlock code has been sent to your registered two factor email address.
        /// </summary>
        public static string RemoveLabelEmailSent {
            get {
                return ResourceManager.GetString("RemoveLabelEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Security.
        /// </summary>
        public static string RemovePageTitle {
            get {
                return ResourceManager.GetString("RemovePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Two Factor.
        /// </summary>
        public static string RemoveTitle {
            get {
                return ResourceManager.GetString("RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification code has been sent to the provided email address.
        /// </summary>
        public static string SuccessMessageSendEmailCode {
            get {
                return ResourceManager.GetString("SuccessMessageSendEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully verified your email two factor code..
        /// </summary>
        public static string SuccessMessageVerifyEmailCode {
            get {
                return ResourceManager.GetString("SuccessMessageVerifyEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully verified your Authenticator code..
        /// </summary>
        public static string SuccessMessageVerifyOtpCode {
            get {
                return ResourceManager.GetString("SuccessMessageVerifyOtpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinCode must be between 4 and 8 digits.
        /// </summary>
        public static string ValidationErrorMessageInvalidPinCode {
            get {
                return ResourceManager.GetString("ValidationErrorMessageInvalidPinCode", resourceCulture);
            }
        }
    }
}
